### ISSUE TITLE
Server freeze

### ISSUE THREAD

**Issue by Darkere** [Direwolf20-MC/MiningGadgets#65]
Server froze to this message in the logs
```
[11:40:38] [Server thread/ERROR] [minecraft/Chunk]: A TileEntity type com.direwolf20.mininggadgets.common.tiles.RenderBlockTileEntity has thrown an exception trying to write state. It will not persist, Report this to the mod author
java.lang.NullPointerException: null
at net.minecraft.nbt.CompoundNBT.func_186854_a(CompoundNBT.java:119) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches CompoundNBT Transformer,re:mixin,pl:accesstransformer:B}
at com.direwolf20.mininggadgets.common.tiles.RenderBlockTileEntity.func_189515_b(RenderBlockTileEntity.java:267) ~[?:1.3.1] {re:classloading}
at net.minecraft.world.chunk.Chunk.func_223134_j(Chunk.java:426) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:286) ~[?:?] {re:classloading}
at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:685) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
```

Full log if required: https://gist.github.com/Darkere/52ea537c11c9a13c8f48504b84e5d3ec
The error after the mining gadgets one only appeared after killing the server. 

mininggadgets-1.3.1.jar

**Comment by MichaelHillcox** [comment]
I'll take a look thanks :+1:

**Comment by Direwolf20-MC** [comment]
Just pushed a fix, will build shortly.
